config/routes.rb
Rails.application.routes.draw do
#devise_for :users
resources :friends

devise_for :users, path: 'users' 
resources :users#, :only => [:show]

devise_scope :user do
  authenticated :user do
    #root 'home#index', as: :authenticated_root
    root 'friends#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

  get 'home/about'
  get 'users/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
    @gimme_user = User.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to edit this friend, punk!" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #Index page
  end

  def about
    #About Page
    @gimme_friend = User.all
    @gimme_user = User.all
    @about_me = "My name is Jamie..."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end

	def index 
		@users = User.all 
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div class="alert alert-warning" role="alert">
      <h2 class="alert-heading"><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div style="width: 22rem;" class="text-center">

  <div class="mb-3">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div class="mb-3">

  <div class="mb-3">
    <%= form.text_field :email, class:"form-control", placeholder:"example@mail.com" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter Handle" %>
  </div>

    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type:"hidden" %>

  <div class="mb-3">
    <%= form.submit class:"btn btn-primary" %>
  </div>

</div>

<% end %>

app/views/friends/_friend.html.erb
<tr id="<%= dom_id friend %>">
  <td>
    <% @full_name = friend.first_name + " " + friend.last_name %>
    <%= link_to @full_name, friend %> 

  </td>

  <td>
    <%= friend.email %>
  </td>

  <td>
    <%= friend.phone %>
  </td>

  <td>
    <%= friend.twitter %>
  </td>
    <td>
    <% showUser = friend.user_id - 1 %>
    <%= @gimme_user[showUser].first_name %>
  </td>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>
<br />
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-dark" %> |
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/index.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
      <tr>
        <th>Name</th>
        <th>Email</th> 
        <th>Phone</th>
        <th>Twitter</th>
        <th>Created By</th>
        <th colspan="1"></th>
      </tr>
  </thead>

  <tbody>
   <% @friends.each do |friend| %>
      <%= render friend %>
      <td>
        <%= button_to "Destroy", friend, method: :delete, class:"btn btn-outline-danger", data: { turbo: false } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New friend", new_friend_path, class:"btn btn-primary" %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>
<br />
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/show.html.erb
<div id="<%= dom_id @friend %>" class="p-5 mb-4 bg-light rounded-3">
  <h2 class="display-5 fw-bold"> <%= @friend.first_name %> <%= @friend.last_name %> </h2>

  <p>
    <%= @friend.email %> | <%= @friend.phone %> | Twitter: <a href="http://twitter.com/<%= @friend.twitter %>">@<%= @friend.twitter %></a>
  </p>

  <div>
    <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-primary" %> 
    <%= link_to "Back to friends", friends_path, class:"btn btn-secondary"%><br />

    <%= button_to "Destroy this friend", @friend, class:"btn btn-danger", method: :delete %>
  </div>


</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <%= link_to 'The World: Friends', authenticated_root_path, class:"navbar-brand" %>
    <% #link_to 'CC2', font_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'New Friend', new_friend_path, class:"nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav d-flex">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-fill"></i> Welcome, <%= current_user.first_name %>!
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to "Show Profile", current_user, class:"dropdown-item", data: { turbo: false } %></li>
            <li> <%= link_to 'Edit Profile', edit_user_registration_path, class:"dropdown-item", data: { turbo: false } %></li>
            <li><%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class:"dropdown-item" %></li>
          </ul>
        </li>
      </ul>
     
    </div>
  </div>
</nav>

<% #if user_signed_in? %>
<% #end %>

app/views/home/about.html.erb
<h1>About Us</h1>

<p>
	<%= @about_me %> <br />
	This site was created by <%= @gimme_user[0].first_name %> <%= @gimme_user[0].last_name %> on <%= @gimme_user[0].created_at %>.<br />
	There are currently <%= @gimme_user.count %> registered users and <%= @gimme_friend.count + 1 %> friends added to the database.
</p>

<p> 
	IF YOU WANNA SHOW DATA ON THE PAGE,<br />
	PASS THE VARIABLES THROUGH THE CONTROLLERS, NERD!
</p>

app/views/home/index.html.erb
<h1>Hello World</h1>
This is my first Rails page!

<%= link_to "current_user_show", current_user %>

app/views/home/old/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">

    <%= link_to 'The World: Friends Center', friends_path, class:"navbar-brand" %>
    <% #link_to 'CC2', font_path, class:"navbar-brand" %>
    

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Show Friends', friends_path, class:"nav-link" %>
        </li>
        
        <!-- Devise -->
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'New Friend', new_friend_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
        </li>
        <% end %>


        <!-- / Devise -->
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_alerts.html.erb
<% flash.each do |type, msg| %>
      <br />
    <% if notice  %>
      <div class="alert alert-info alert-dismissible fade show" role="alert">
    <% elsif alert %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <% else %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <% end %>
        <%= msg %> 
     </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>CYBERCONNECT2</title>
    <!-- Bootstrap Meta Tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Rails Meta Tags -->
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <!-- Rails CSS -->
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <!-- Rails JS -->
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <% if user_signed_in? %>
      <%= render 'home/header' %>
      <p>&nbsp;</p>
      <div class="container">
        <noscript><h1 class="alert alert-danger" role="alert">You must enable Javascript to veiw this page properly!</h1></noscript>
        <% if notice %>
          <%= render 'layouts/alerts' %>
        <% end %>
        <!-- [Yield] -->
        <%= yield %>
        <!-- [/Yeild] -->
    <% else %>
        <!-- [Yield] -->
        <%= yield %>
        <!-- [/Yeild] -->
    <% end %>

   


 <!-- Bootstrap&Popper JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/old/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>CYBERCONNECT2</title>
    <!-- Bootstrap Meta Tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Rails Meta Tags -->
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- Rails CSS -->
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <!-- Rails JS -->
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <% if user_signed_in? %>
      <%= render 'home/header' %>
      <p>&nbsp;</p>
      <div class="container">
        <noscript><h1 class="alert alert-danger" role="alert">You must enable Javascript to veiw this page properly!</h1></noscript>
        <% if notice %>
          <%= render 'layouts/alerts' %>
        <% end %>
    
      <!-- [Yield] -->
      <%= yield %>
      <!-- [/Yeild] -->
    </div>

    </script>
  <% else %>
    <%= yield %>
  <% end %>
  
 <!-- Bootstrap&Popper JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/index.html.erb
<h2> Active Users </h2>

<table class="table table-striped table-bordered table-hover">
	<thead class="table-dark">
		<th colspan=2>Name</th>
		<th>Email</th>
		<th></th>
	</thead>
	
<% @users.each do |user| %>
	<tr>
		<td><%= user.first_name %></td>
		<td><%= user.last_name %></td>
		<td><%= user.email %></td>
		<td> <%= link_to "Show", user %></td>
	</tr>
<% end %>
</table>

app/views/users/show.html.erb
<h2> Showing profile for <%= @user.first_name %> <%= @user.last_name %></h2>

<%= @user.email %>